#pragma warning disable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using XmppSharp.Collections;
using static XmppSharp.Expat.Native;

namespace XmppSharp.Expat;

public enum Error
{
    NONE,
    NO_MEMORY,
    SYNTAX,
    NO_ELEMENTS,
    INVALID_TOKEN,
    UNCLOSED_TOKEN,
    PARTIAL_CHAR,
    TAG_MISMATCH,
    DUPLICATE_ATTRIBUTE,
    JUNK_AFTER_DOC_ELEMENT,
    PARAM_ENTITY_REF,
    UNDEFINED_ENTITY,
    RECURSIVE_ENTITY_REF,
    ASYNC_ENTITY,
    BAD_CHAR_REF,
    BINARY_ENTITY_REF,
    ATTRIBUTE_EXTERNAL_ENTITY_REF,
    MISPLACED_XML_PI,
    UNKNOWN_ENCODING,
    INCORRECT_ENCODING,
    UNCLOSED_CDATA_SECTION,
    EXTERNAL_ENTITY_HANDLING,
    NOT_STANDALONE,
    UNEXPECTED_STATE,
    ENTITY_DECLARED_IN_PE,
    FEATURE_REQUIRES_XML_DTD,
    CANT_CHANGE_FEATURE_ONCE_PARSING,
    UNBOUND_PREFIX,
    UNDECLARING_PREFIX,
    INCOMPLETE_PE,
    XML_DECL,
    TEXT_DECL,
    PUBLICID,
    SUSPENDED,
    NOT_SUSPENDED,
    ABORTED,
    FINISHED,
    SUSPEND_PE,
    RESERVED_PREFIX_XML,
    RESERVED_PREFIX_XMLNS,
    RESERVED_NAMESPACE_URI,
    INVALID_ARGUMENT,
    NO_BUFFER,
    AMPLIFICATION_LIMIT_BREACH,
    NOT_STARTED,
}
