using System.Runtime.CompilerServices;
using XmppSharp.Attributes;
using XmppSharp.Xml;

namespace XmppSharp.Protocol.Base;

/// <summary>
/// Represents the root element of an XMPP stream.
/// </summary>
/// <remarks>
/// This element is used to establish a connection between two XMPP entities and serves as the container for all subsequent stanzas exchanged during the session.
/// </remarks>
[Tag("stream", Namespaces.Stream)]
[Tag("stream:stream", Namespaces.Stream)]
public class Stream : DirectionalElement
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Stream"/> class.
    /// </summary>
    public Stream() : base("stream:stream", Namespaces.Stream)
    {
        Version = "1.0";
        DefaultNamespace = Stanza.DefaultNamespace;
    }

    /// <summary>
    /// Gets or sets the default namespace which is typically set to the namespace used for XMPP stanzas.
    /// </summary>
    public string? DefaultNamespace
    {
        get => GetAttribute("xmlns");
        set => SetAttribute("xmlns", value);
    }

    /// <summary>
    /// Gets or sets the unique identifier for the stream.
    /// </summary>
    /// <remarks>
    /// This attribute is typically generated by the server when a client initiates a connection and is used to track the session.
    /// </remarks>
    public string? Id
    {
        get => GetAttribute("id");
        set => SetAttribute("id", value);
    }

    /// <summary>
    /// Generates a new unique identifier for the stream.
    /// </summary>
    [MethodImpl(MethodImplOptions.NoInlining)]
    public void GenerateId()
    {
        Id = Guid.NewGuid().ToString("n");
    }

    /// <summary>
    /// Gets or sets the language of the stream content, specified using the standard XML language tag format.
    /// </summary>
    public string? Language
    {
        get => GetAttribute("xml:lang");
        set => SetAttribute("xml:lang", value);
    }

    /// <summary>
    /// Gets or sets the version of the XMPP protocol being used for the stream, typically in the format "1.0".
    /// </summary>
    public string? Version
    {
        get => GetAttribute("version");
        set => SetAttribute("version", value);
    }

    /// <summary>
    /// Writes the opening tag of the stream element to the specified DomWriter, including all attributes but excluding the closing tag.
    /// </summary>
    /// <param name="writer">The DomWriter to which the stream element will be written.</param>
    public override void WriteTo(DomWriter writer)
    {
        writer.BeginNamespaceScope();
        WriteStartElement(writer);
        writer.EndNamespaceScope();
    }
}