using XmppSharp.Attributes;

namespace XmppSharp.Protocol;

[XmppEnum]
public enum MessageType
{
	/// <summary>
	/// The message is sent in the context of a one-to-one chat conversation. A compliant client <b>should</b> present the message in an interface enabling one-to-one chat between the two parties, including an appropriate conversation history.
	/// </summary>
	[XmppMember("chat")]
	Chat,

	/// <summary>
	/// An error has occurred related to a previous message sent by the sender. A compliant client <b>should</b> present an appropriate interface informing the sender of the nature of the error.
	/// </summary>
	[XmppMember("error")]
	Error,

	/// <summary>
	/// The message is sent in the context of a multi-user chat environment. A compliant client <b>should</b> present the message in an interface enabling many-to-many chat between the parties, including a roster of parties in the chatroom and an appropriate conversation history.
	/// </summary>
	[XmppMember("groupchat")]
	GroupChat,

	/// <summary>
	/// The message is probably generated by an automated service that delivers or broadcasts content (news, sports, market information, RSS feeds, etc.). No reply to the message is expected, and a compliant client <b>should</b> present the message in an interface that appropriately differentiates the message from standalone messages, chat sessions, or groupchat sessions (e.g., by not providing the recipient with the ability to reply).
	/// </summary>
	[XmppMember("headline")]
	Headline,

	/// <summary>
	/// The message is a single message that is sent outside the context of a one-to-one conversation or groupchat, and to which it is expected that the recipient will reply. A compliant client <b>should</b> present the message in an interface enabling the recipient to reply, but without a conversation history.
	/// </summary>
	[XmppMember("normal")]
	Normal
}